# Generated by Django 5.1.3 on 2024-11-23 19:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('credit_card', 'Credit Card'), ('digital_wallet', 'Digital Wallet'), ('cash', 'Cash')], max_length=20)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spent_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_balance', models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=10, null=True)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_mode', models.CharField(choices=[('debit_card', 'Debit Card'), ('mobile_wallets', 'Mobile Wallets'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('neft', 'NEFT'), ('imps', 'IMPS'), ('other', 'Other')], default='other', max_length=100)),
                ('category', models.CharField(choices=[('needs', 'Needs'), ('wants', 'Wants'), ('savings', 'Savings')], default='needs', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expense.paymentmethod')),
            ],
        ),
    ]
