# Generated by Django 5.1.3 on 2024-11-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('needs', 'Needs'), ('wants', 'Wants'), ('savings', 'Savings'), ('income', 'Income')], default='needs', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='minimum_balance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='  Enter 0 for Zero Balance Accounts.', max_digits=10, null=True),
        ),
    ]
